config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "www.fitrackular.com"
  root 'businesses#welcome'

  get '/account_activations/send_activation', to: 'account_activations#send_activation', as: :account_activations_send_activation
  get '/account_activations/blacklist', to: 'account_activations#blacklist', as: :account_activations_blacklist
  get '/account_activations/:id/', to: 'account_activations#activate', :constraints => { :id => /[^\/]+/ }, as: :account_activations_activate

  resources :subscriptions
  patch 'subscribe' => 'subscriptions#subscribe', via: [:patch, :put], as: :subscriptions_subscribe
  patch 'approve' => 'subscriptions#approve', via: [:patch, :put], as: :subscriptions_approve
  patch 'unsubscribe' => 'subscriptions#unsubscribe', via: [:patch, :put], as: :subscriptions_unsubscribe
  patch 'deactivate' => 'subscriptions#deactivate', via: [:patch, :put], as: :subscriptions_deactivate

  get 'auth/failure', to: redirect('/') #Redirect to _RETRY_
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'

  get '/embedded_login', to: 'sessions#new_embedded'
  get '/embedded_signup', to: 'users#new_embedded'

  delete '/logout',  to: 'sessions#destroy'

	resources :users, except: [:index]

  get    '/settings',to: 'users#settings'
  get    '/users',to: 'users#admin_index'

  patch    '/users/:id/resync_google' => 'users#resync_google', via: [:patch, :put], as: :users_resync_google
	patch    '/users/:id/approve' => 'users#approve', via: [:patch, :put], as: :users_approve

  resources :friends, 						only: [:create, :destroy]
  patch    '/friends/:id/approve' => 'friends#approve', via: [:patch, :put], as: :friends_approve

  get 'auth/:provider/callback', to: 'sessions#google_authorize'

  resources :reminders
  get ':id/reminders/:id/add', to: 'reminders#add', as: :reminders_add
  get 'reminders/:id/view', to: 'reminders#view', as: :reminders_view

  resources :invoice_items
  resources :user_rates

  patch    ':id/invoices/:id/set_processed' => 'invoices#set_processed', via: [:patch, :put], as: :invoices_set_processed
  patch    ':id/invoices/:id/set_unprocessed' => 'invoices#set_unprocessed', via: [:patch, :put], as: :invoices_set_unprocessed
  patch    ':id/invoices/:id/settle_month' => 'invoices#settle_month', via: [:patch, :put], as: :invoices_settle_month
  patch ':id/invoices/:id/reconcile' => 'invoices#reconcile', via: [:patch, :put], as: :invoices_reconcile

  get ':id/home', to: 'businesses#home', as: :business_home
  get ':id/view_available_groupsessions_embedded', to: 'businesses#view_available_groupsessions_embedded', as: :view_available_groupsessions_embedded

  get ':id/dashboard', to: 'businesses#dashboard', as: :business_dashboard
  get ':id/calendar(/:mode/:date)' => 'businesses#calendar', as: :businesses_calendar
  get ':id/get_month(/:date/:token)' => 'businesses#get_month', as: :businesses_get_month

  resources :suggestions
  resources :invoice_months

  resources :businesses, path: '/' do
    get 'edit/?tab=sessions', to: 'businesses#edit', as: :edit_sessions
    patch 'change_histories/mark_all_read', to: 'change_histories#mark_all_read', as: :mark_all_read

    resources :invoice_items,    only: [:create, :index, :new]
    resources :items
    resources :constants
    resources :taxes
    resources :memberships
    resources :reminders,    only: [:create, :index, :new]
    resources :rates, 							only: [:create]
    resources :workout_sessions
    resources :user_rates,          only: [:create, :index]
    resources :payments
  	resources :invoices

    patch    ':id/invoices/:id/pay_with_credit' => 'invoices#pay_with_credit', via: [:patch, :put], as: :invoices_pay_with_credit
    patch ':date/invoice_months/flip' => 'invoice_months#flip', via: [:patch, :put], as: :invoice_months_flip
    patch ':date/invoice_months/recalculate' => 'invoice_months#recalculate', via: [:patch, :put], as: :invoice_months_recalculate

    patch    '/users/:id/new_gdrive_workout' => 'users#new_gdrive_workout', via: [:patch, :put], as: :users_new_gdrive_workout
    get '/users/new', to: 'users#new_modal', as: :users_new_modal
    post '/users/', to: 'users#admin_create'
  	resources :users

    get '/users/:id/edit_modal', to: 'users#edit_modal', as: :users_edit_modal


    get '/login',   to: 'sessions#new'
    post '/login',   to: 'sessions#create'

    get '/embedded_login', to: 'sessions#new_embedded'
    get '/embedded_signup', to: 'users#new_embedded'
    post '/embedded_signup', to: 'users#create'
    get '/settings', to: 'users#settings'

    get '/sharks', to: 'businesses#sharks', as: :sharks #testing temporary

    get ':id/workout_sessions/add', to: 'workout_sessions#add', as: :workout_sessions_add
    get '/workout_sessions/:id/book_session(/:date)', to: 'workout_sessions#book_groupsession', as: :book_groupsession
    get '/workout_sessions/:id/cancel_session', to: 'workout_sessions#cancel_groupsession', as: :cancel_groupsession


    resources :user_workouts do
      collection do
        put :setoptions
      end
    end

    resources :user_workouts,				only: [:update, :edit]

    get '/workout_sessions/:id/view', to: 'workout_sessions#view', as: :workout_sessions_view
    patch    '/workout_sessions/:id/success' => 'workout_sessions#success', via: [:patch, :put], as: :workout_sessions_success
    patch    '/workout_sessions/:id/approve' => 'workout_sessions#approve', via: [:patch, :put], as: :workout_sessions_approve
    patch    '/workout_sessions/:id/approveallthismonth' => 'workout_sessions#approveallthismonth', via: [:patch, :put], as: :workout_sessions_approveallthismonth
    patch    '/workout_sessions/:id/approveallfollowing' => 'workout_sessions#approveallfollowing', via: [:patch, :put], as: :workout_sessions_approveallfollowing
    patch    '/workout_sessions/:id/approveupto' => 'workout_sessions#approveupto', via: [:patch, :put], as: :workout_sessions_approveupto
    patch    '/workout_sessions/:id/reschedule' => 'workout_sessions#reschedule', via: [:patch, :put], as: :workout_sessions_reschedule
    patch    '/workout_sessions/:id/cancel' => 'workout_sessions#cancel', via: [:patch, :put], as: :workout_sessions_cancel
    patch    '/workout_sessions/:id/noshow' => 'workout_sessions#noshow', via: [:patch, :put], as: :workout_sessions_noshow
    patch    '/workout_sessions/:id/remove/:date' => 'workout_sessions#remove', via: [:patch, :put], as: :workout_sessions_remove
    patch    '/workout_sessions/:id/removefollowing(/:date)' => 'workout_sessions#removefollowing', via: [:patch, :put], as: :workout_sessions_removefollowing
    patch    '/workout_sessions/:id/removeall' => 'workout_sessions#removeall', via: [:patch, :put], as: :workout_sessions_removeall
    patch    '/workout_sessions/:id/unlink' => 'workout_sessions#unlink', via: [:patch, :put], as: :workout_sessions_unlink
    patch    '/workout_sessions/:id/sync_google_event' => 'workout_sessions#sync_google_event', via: [:patch, :put], as: :workout_sessions_sync_google_event
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper

  def bookable_collection
    bookable_collection = {}
    bookable_collection["Session"] = WorkoutSession.workout if @business.allow_private_session?
    bookable_collection["Group Session"] = WorkoutSession.groupworkout if @business.allow_group_session?
    bookable_collection["Personal Event"] = WorkoutSession.event

    bookable_collection
  end

  def weekly?
    @weekly
  end

  def monthly?
    @monthly
  end

  def user_type?(user)
    if @business.view_as_employee?(user)
      "employee"
    else
      "client"
    end
  end

  def get_events_json
    workout_sessions = WorkoutSession.where(:business => @business,)

    only = [ :id, :date, :duration, :bfr_from, :bfr_to ]

    workout_sessions.to_json(only: only).html_safe
  end

  def render_events_for_employee(event, date, user)
    case event.eventtype
    when WorkoutSession.workout
      return render('workout_admin', workout: event)
    when WorkoutSession.event
      return render('event_admin', event: event)
    when WorkoutSession.groupworkout
      return render('groupworkout_admin', groupworkout: event)
    when -WorkoutSession.groupworkout
      return render('repeating_groupworkout_admin', groupworkout: event, date: date)
    end
  end
  def render_events_for_client(event, date, user)
    case event.eventtype
    when WorkoutSession.workout
      return render('workout_client', workout: event)
    when WorkoutSession.event
      return render('event_client', event: event)
    when WorkoutSession.groupworkout
      return render('groupworkout_client', groupworkout: event)
    when -WorkoutSession.groupworkout
      return render('repeating_groupworkout_client', groupworkout: event, date: date)
    end
  end

  def calendar_weekly_time_block(date = Time.zone.now, &block)
    CalendarWeekly.new(self, date, block, nil, nil).time_block
  end

  def calendar_weekly_events_block(&block)
    CalendarWeekly.new(self, nil, block, nil, nil).flex_containers
  end

  def calendar_weekly_horiz_grid(date, &block)
    CalendarWeekly.new(self, date, block, nil, nil).horizontal_grid
  end

  def calendar_weekly_day(date = Time.zone.now.to_date, for_user, events, &block)
    CalendarWeekly.new(self, date, block, @business.view_as_employee?(for_user), events).day_column(date)
  end

  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block, @business.view_as_employee?(@for_user)).div
  end

  def reminders_for(date = Date.today, for_user, reminders, &block)
    CalendarReminder.new(self, date, reminders, block).day_reminders
  end

  def events_for(date = Date.today, events, &block)
    CalendarEvent.new(self, date, events, block).day_events
  end

  def business_color_css(business)
    business.color.present? ? (business.color) : 'white'
  end

  def overflow
    content_tag :table, class: "overflow" do
        content_tag :tr, class: "overflow" do
          content_tag :td, class: "overflow" do
            yield
        end
      end
    end
  end

  ###
  def end_time_for(w, busy = false)
  duration = w.duration
    if @business.view_as_employee?(current_user)
      return duration.strftime("%l:%M%P").chomp("m") unless w.duration.min == 0
      return duration.strftime("%l%P").chomp("m")
    else
      duration = duration + w.bfr_to.minutes if busy
      return duration.strftime("%l:%M%p") unless duration.min == 0
      return duration.strftime("%l%p")
    end
  end

  def start_time_for(w, busy = false)
    date = w.date
    if @business.view_as_employee?(current_user)
      return date.strftime("%l:%M%P").chomp("m") unless w.date.min == 0
      return date.strftime("%l%P").chomp("m")
    else
      date = date - w.bfr_from.minutes if busy
      return date.strftime("%l:%M%p") unless date.min == 0
      return date.strftime("%l%p")
    end
  end

  def event_time_for(w, busy = false)
    s = start_time_for(w, busy)
    e = end_time_for(w, busy)
    if (w.date + 1.hour == w.duration && @business.view_as_employee?(current_user))
      s
    else
      s + " &ndash; " + e
    end
  end

  def event_time_full_for(w)
    start_time = w.date
    end_time = w.duration
    start_time.strftime("%l:%M%P") + " &ndash; " + end_time.strftime("%l:%M%P")
  end

  def event_time_from_to(w1, w2, busy = false)
      s = start_time_for(w1, true)
      e = end_time_for(w2, true)
      s + " &ndash; " + e
  end

  def end_to_start(w1, w2, busy = false)
    if (w1 && w2)
      if ensure_one_hour_between_events(w1, w2)
        e = end_time_for(w1, true)
        s = start_time_for(w2, true)
        e + " &ndash; " + s
      else
        nil
      end
    elsif w1
      e = end_time_for(w1, true)
      e + " &ndash; " + "Midnight"
    else
      s = start_time_for(w2, true)
      "Morning" + " &ndash; " + s
    end
  end

  def ensure_one_hour_between_events (w1, w2)
    (w2.date - w2.bfr_from.minutes) > (w1.duration + w1.bfr_to.minutes + 1.hour)
  end

  def next_user_sesh uid
    ws = WorkoutSession.joins("JOIN user_workouts ON workout_sessions.id = user_workouts.workout_session_id AND user_workouts.user_id =" + uid.to_s).where("date > ?", Time.zone.now).reorder(:date).first
  end

  def next_event
    WorkoutSession.where("date >= ? AND eventtype = ?", Time.zone.now, 1)
  end

  def today?(datetime)
    datetime.to_date == Time.zone.now.to_date
  end

  def next_month
    schedule_path + '?month=' + (@m + 1).to_s
  end

  def previous_month
    schedule_path + '?month=' + (@m + -1).to_s
  end

  def repeat_groupworkout_status(ws, date, tooltip = false)
    if date > Time.zone.now
      status = "unchecked upcoming"
      text = "Session coming up"
    else
      status = "ok success"
      text = "Session successful"
    end

    if tooltip
      return "<span class='glyphicon glyphicon-#{status}'></span> <small id='small_status'> #{text}</small>"
    else
      return "<span class='glyphicon glyphicon-#{status}'></span>"
    end
  end

  def repeat_on_to_weekdays(repeat_on)
    out = ""

    arr = repeat_on.split("")
    first = true
    arr.each_with_index do |char, index|
      if char == "1"
        (out << ", ") unless first
        (out << Date::ABBR_DAYNAMES[index])
        first = false
      end
    end

    out
  end

  def workout_status(ws, reschedules_list = nil, tooltip = false)
    @rescheduled = nil
    reschedules_list = Reschedule.all unless reschedules_list
    text = nil

    if reschedules_list.where(:link => ws.id).empty?
      status = "unchecked upcoming"
      text = "Session coming up"

      case ws.status
        when WorkoutSession::STATUS["ok"]
          if Time.zone.now > ws.date
            status = "ok success"
            text = "Session successful"
          end
        when WorkoutSession::STATUS["reschedule"]
          @rescheduled = true
          if @workout_sessions_all && !(rs = reschedules_list.where(:workout_session_id => ws.id)).empty?
            if !(w = @workout_sessions_all.where(:id => rs.first.link)).empty?
              rescheduled = w.first.date.strftime("%-d %b, %Y")
              rescheduled_title = "Rescheduled to"
            end
          end
          status = "share-alt rescheduled_from"
          text = "Session rescheduled to #{rescheduled}"
        when WorkoutSession::STATUS["cancel"]
          status = "remove cancelled"
          text = "Session cancelled"
        when WorkoutSession::STATUS["noshow"]
          status = "remove-sign noshow"
          text = "Session was a no show"
        when WorkoutSession::STATUS["draft"]
          status = "flag draft"
          text = "Session pending approval"
      end
    else
      if @workout_sessions_all && !(rs = reschedules_list.where(:link => ws.id)).empty?
        if  !(w = @workout_sessions_all.where(:id => rs.first.workout_session_id)).empty?
          rescheduled = w.first.date.strftime("%-d %b, %Y")
          rescheduled_title = "Rescheduled from"
        end
      end

      status = "unchecked upcoming_re"
      text = "Session coming up"

      case ws.status
        when WorkoutSession::STATUS["ok"]
          if Time.zone.now > ws.date
            status = "exclamation-sign success_re"
            text = "Session successful"
          end
        when WorkoutSession::STATUS["reschedule"]
          status = "share-alt rescheduled_from"
          text = "Session coming up."
          text += "Rescheduled from #{rescheduled}" if rescheduled
        when WorkoutSession::STATUS["cancel"]
          status = "remove cancelled_re"
          text = "Session cancelled"
        when WorkoutSession::STATUS["noshow"]
          status = "remove-sign noshow_re"
          text = "Session was a no show"
        when WorkoutSession::STATUS["draft"]
           status = "flag draft"
          text = "Session pending approval"
       end
    end

    if tooltip
      return "<span class='glyphicon glyphicon-#{status}' data-title='#{rescheduled_title}' data-content='#{rescheduled}' data-html='true' data-toggle='popover' data-trigger='hover' data-placement='top'></span> <small id='small_status'> #{text}</small>"
    else
      return "<span class='glyphicon glyphicon-#{status}' data-title='#{rescheduled_title}' data-content='#{rescheduled}' data-html='true' data-toggle='popover' data-trigger='hover' data-placement='top'></span>"
    end
  end

  def get_buffer(ws)
    (ws.bfr_from.to_s || "0") + "/" + (ws.bfr_to.to_s || "0")
  end

  def reminder_popover(ws)
    val = ""
    ws.reminders.where(:user => current_user).each do |r|
      val += r.memo + "</br>"
    end

    return val
  end

	def current_date(date)
		date.beginning_of_day..date.end_of_day
	end

	def start_and_end_day_wrap (date, events, &block)
		if events.any?
			start_day_wrap(date, events).html_safe + capture(&block) + end_day_wrap(date, events).html_safe
		elsif date > Time.zone.now
			available_all_day_wrap.html_safe
		end
	end

	def start_day_wrap (date, events)
		if (date > Time.zone.now) && (events.first.date > events.first.date.beginning_of_day + 1.hour)

app/views/businesses/_workout_admin.html.erb
<tr class="alert">
  <td class="daysettings" style=" <%= "border-left: 3px #fea410 solid;" if !workout.memo.blank? %> ">
    <div class="dropdown" id="print">
      <button style=" border: none; background: none; padding-left:2px; padding-right:2px; " id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <%= raw(workout_status(workout, @reschedules)) %>
      </button>

      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <li>
          <%= link_to reminders_add_path(workout), remote: true, 'data-toggle' => 'modal', 'data-target' => "#reminders-view" do %>
          Add reminder
        <% end %>
        </li>
        <li class="divider", id: "headertext" ></li>
      <% if workout.status != WorkoutSession::STATUS["draft"] %>
        <% unless workout.status == WorkoutSession::STATUS["ok"] %>
          <% lbl = (Date.today > workout.date) ? "Success" : "Upcoming" %>
          <li>
          <%= link_to lbl, business_workout_sessions_success_path(@business.slug, workout), method: :patch %>
          </li>
        <% end %>

        <% unless workout.status == WorkoutSession::STATUS["noshow"] %>
          <li>	<!-- No show -->
            <%= link_to "No show", business_workout_sessions_noshow_path(@business.slug, workout), method: :patch %>
          </li>
        <% end %>

        <% unless workout.status == WorkoutSession::STATUS["cancel"] %>
          <li>	<!-- Cancel -->
            <%= link_to "Cancel", business_workout_sessions_cancel_path(@business.slug, workout), method: :patch %>
          </li>
        <% end %>
      <% else %>
        <% unless workout.status == WorkoutSession::STATUS["ok"] %>
          <li>
            <%= link_to "Approve", business_workout_sessions_approve_path(@business.slug, workout), method: :patch %>
          </li>
          <li>
            <%= link_to "Approve up to", business_workout_sessions_approveupto_path(@business.slug, workout), method: :patch %>
          </li>
          <li>
            <%= link_to "Approve following", business_workout_sessions_approveallfollowing_path(@business.slug, workout), method: :patch %>
          </li>
          <li>
            <%= link_to "Approve all this month", business_workout_sessions_approveallthismonth_path(@business.slug, workout), method: :patch %>
          </li>
        <% end %>
      <% end %>
        <li class="divider", id: "headertext" ></li>
        <li><%= link_to "Remove", business_workout_session_path(@business.slug, workout), method: :delete,
                data: { confirm: "Remove session?" } %></li>
        <li><%= link_to "Remove following sessions", business_workout_sessions_removefollowing_path(@business.slug, workout), method: :patch,
                data: { confirm: "Remove following sessions?" } %></li>
        <li><%= link_to "Remove all sessions", business_workout_sessions_removeall_path(@business.slug, workout), method: :patch,
                data: { confirm: "Remove all sessions?" } %></li>
      </ul>
    </div>
  </td>
  <td class="day <%= workout.group_id %>">
    <%= overflow do %>
      <% if workout.status == 1 || workout.status == 2 %>
        <%= raw("<strike>") %>
      <% end %>

      <%= link_to business_workout_sessions_view_path(@business.slug, workout), remote: true, 'data-toggle' => 'modal', 'data-target' => "#workout-sessions-view" do %>

        <b> <%= raw(event_time_for workout) %></b>

        <small> <%= get_buffer(workout) %> </small>

        <% if workout.user_workouts.empty? %>
          (no clients)
        <% else %>
          <% comma = "" %>

            <% user_workouts = workout.user_workouts %>

            <% user_workouts.each do |uw| %>
              <%= comma %>
                <% if @rescheduled %>
                  <% user_status = "" %>
                <% elsif !uw.paid && uw.cost && uw.cost > 0 %>
                  <% user_status = "alert alert-warning" %>
                <% elsif uw.paid && uw.cost %>
                  <% user_status ="alert alert-success" %>
                <% else %>
                  <% user_status ="alert alert-info" %>
                <% end %>

                <span class=" <%= user_status %> ">
                  <%# uw.user.name(upcase: true) %>
                  <%= uw.user.shortname %>
                </span>
              <% comma = "," %>
            <% end %>
        <% end %>
      <% end %>

      <% if workout.status == 1 || workout.status == 2 %>
        <%= raw("</strike>") %>
      <% end %>

      <% if workout.group %>
        <span class="glyphicon glyphicon-repeat repeat-glyph-instance"></span>
      <% end %>
    <% end %>

  </td>
</tr>

app/views/businesses/new.html.erb
<div class="container-fluid" style="background-color: #F3F3F3;">
<h1>New Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', businesses_path %>
</div>

app/views/businesses/welcome.html.erb
<% if current_user %>
  <div class="jumbotron">
    <div class="container">
        <% Business.all.in_groups_of(3).each do |bgroup| %>
          <div class="row">
            <% bgroup.each do |business| %>
              <% if business %>
                <div class="col-md-3">
                  <div class="card">
                    <% if business.avatar.url %>
                      <%= image_tag(business.avatar.url, alt: 'Logo', class: 'card-img') %>
                    <% else %>
                      <div class="card-img" style="width: 100%; height: 100%;">
                      </div>
                      <%= image_tag("undefined-avatar.png", alt: 'Logo', class: 'card-img') %>
                    <% end %>
                    <div class="container">
                      <h4><%= link_to business.name, businesses_calendar_path(business.slug) %></h4>
                      <p>
                        <small>
                          <% if business.owner == current_user %>
                            (Owner)
                          <% else %>
                          <% if (subscription = business.get_subscription(current_user.id)) %>
                            <% if subscription.subscribed? %>
                              <%= link_to "Unsubscribe", subscriptions_unsubscribe_path(:id => subscription.id), method: :patch, data: { confirm: "Unsubscribe from #{ business.name }?" } %>
                            <% elsif subscription.pending? %>
                              <%= link_to "Pending (cancel)", subscriptions_unsubscribe_path(:id => subscription.id), method: :patch, data: { confirm: "Unsubscribe from #{ business.name }?" } %>
                            <% elsif subscription.deactivated? || subscription.unsubscribed? %>
                              <%= link_to "Subscribe", subscriptions_subscribe_path(:business_id => business.id, :user_id => current_user.id), method: :patch %>
                            <% end %>
                          <% else %>
                            <%= link_to "Subscribe", subscriptions_subscribe_path(:business_id => business.id, :user_id => current_user.id), method: :patch %>
                          <% end %>
                          <% end %>
                        </small>
                      </p>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>

<% else %>
  <div class="jumbotron " style="background-color: inherit; height: 600px; color: white;">
    <div class="container">
      <div class="row" style=>
        <div class="col-md-7">
          <h1 style="text-align: left; letter-spacing: .3em; ">PERSONAL TRAINING</h1>
          <hr>
          <h1 style="text-align: left; letter-spacing: .4em; color: #FFA07A;">MADE EASY. </h1>
        </div>
      </div>

      <div class="row" style="margin-top: 50px;">
        <div class="col-md-7">
          <%= link_to "Log in", login_url, class: "btn btn-default btn-lg", style: "font-weight: bold;" %>
          <%= link_to "Sign up", signup_path, class: "btn btn-default btn-lg", style: "color:#FFA07A; font-weight: bold; margin-left: 25px;" %>
        </div>
      </h1>
      </div>

    </div>
  </div>
  <div class="jumbotron" style="background-color: white; height: 100px; margin: 0px; padding: 0px;">
    <div class="container">
      <ul class="nav nav-pills" style="width: 100%;">
        <li role="presentation" class="li-four-points" style="margin: 0px;">
          <a class="a-point" href="#">
            <span class="glyphicon glyphicon-user glyph-point"></span>
            Manage clients
          </a>
        </li>
        <li role="presentation" class="li-four-points" style="margin: 0px;">
          <a class="a-point" href="#">
            <span class="glyphicon glyphicon-calendar glyph-point"></span>
            Schedule sessions
          </a>
        </li>
        <li role="presentation" class="li-four-points" style="margin: 0px;">
          <a class="a-point" href="#">
            <span class="glyphicon glyphicon-usd glyph-point"></span>
            Billing / invoices
          </a>
        </li>
        <li role="presentation" class="li-four-points" style="margin: 0px;">
          <a class="a-point" href="#">
            <span class="glyphicon glyphicon-scale glyph-point"></span>
            Workout history
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="jumbotron" style="height: 500px; margin: 0px; padding-top: 150px;">
    <div class="container">
      <h1>Focus on training, not bookkeeping </h1>
      <p style="text-align: center;"> Keep track of monthly payments with automatically generated invoices. </br>
        F!Trackular keeps track of who pays when, and how much. </p>
    </div>
  </div>

  <div class="jumbotron" style="height: 500px; margin: 0px; padding-top: 150px; background-color: #FFA07A; color: white">
    <div class="container">
      <div class="col-md-9">
        <h1> Let clients book themselves </h1>
        <p style="text-align: center;"> Clients draft a training schedule based on your availability, then you approve it. </br>
          F!Trackular encourages clients to book efficiently. </p>
      </div>
    </div>
  </div>

  <div class="jumbotron" style="height: 500px; margin: 0px; padding-top: 150px; background-color: #3B2F63; color: white">
    <div class="container">
      <div class="col-md-3"></div>
      <div class="col-md-9">
        <h1> Get to know your clients through customized profiles </h1>
        <p style="text-align: center;"> Track training goals, past injuries, and deadlines. </br>
          F!Trackular does it all for you.
          </p>
      </div>
    </div>
  </div>

  <div class="jumbotron" style="height: 500px; margin: 0px; padding-top: 150px;">
    <div class="container">

        <h1> Why wait? </h1>
        <p style="text-align: center;"> <a href="#" style="font-weight: bold;"> Sign up </a> now, and get the full benefits for $25 / month.<p>

    </div>
  </div>
<% end %>
<% if current_user && current_user.admin %>
  <div style="background-color: red; height: 10px; width: 100%"></div>
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#viewGroupSessionsModal">Book Session</button>


  <div style="background-color: blue; height: 10px; width: 100%"></div>

  <div id="viewGroupSessionsModal" class="modal fade" role="dialog">
  </div>

  <script src="https://www.fitrackular.com/jumpingfitnessvictoria/view_available_groupsessions_embedded" type="text/javascript"></script>

<% end %>