config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "www.fitrackular.com"
  root 'businesses#welcome'

  get '/account_activations/send_activation', to: 'account_activations#send_activation', as: :account_activations_send_activation
  get '/account_activations/blacklist', to: 'account_activations#blacklist', as: :account_activations_blacklist
  get '/account_activations/:id/', to: 'account_activations#activate', :constraints => { :id => /[^\/]+/ }, as: :account_activations_activate

  resources :subscriptions
  patch 'subscribe' => 'subscriptions#subscribe', via: [:patch, :put], as: :subscriptions_subscribe
  patch 'approve' => 'subscriptions#approve', via: [:patch, :put], as: :subscriptions_approve
  patch 'unsubscribe' => 'subscriptions#unsubscribe', via: [:patch, :put], as: :subscriptions_unsubscribe
  patch 'deactivate' => 'subscriptions#deactivate', via: [:patch, :put], as: :subscriptions_deactivate

  get 'auth/failure', to: redirect('/') #Redirect to _RETRY_
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'

  get '/embedded_login', to: 'sessions#new_embedded'
  get '/embedded_signup', to: 'users#new_embedded'

  delete '/logout',  to: 'sessions#destroy'

	resources :users, except: [:index]

  get    '/settings',to: 'users#settings'
  get    '/users',to: 'users#admin_index'

  patch    '/users/:id/resync_google' => 'users#resync_google', via: [:patch, :put], as: :users_resync_google
	patch    '/users/:id/approve' => 'users#approve', via: [:patch, :put], as: :users_approve

  resources :friends, 						only: [:create, :destroy]
  patch    '/friends/:id/approve' => 'friends#approve', via: [:patch, :put], as: :friends_approve

  get 'auth/:provider/callback', to: 'sessions#google_authorize'

  resources :reminders
  get ':id/reminders/:id/add', to: 'reminders#add', as: :reminders_add
  get 'reminders/:id/view', to: 'reminders#view', as: :reminders_view

  resources :invoice_items
  resources :user_rates

  patch    ':id/invoices/:id/set_processed' => 'invoices#set_processed', via: [:patch, :put], as: :invoices_set_processed
  patch    ':id/invoices/:id/set_unprocessed' => 'invoices#set_unprocessed', via: [:patch, :put], as: :invoices_set_unprocessed
  patch    ':id/invoices/:id/settle_month' => 'invoices#settle_month', via: [:patch, :put], as: :invoices_settle_month
  patch ':id/invoices/:id/reconcile' => 'invoices#reconcile', via: [:patch, :put], as: :invoices_reconcile

  get ':id/home', to: 'businesses#home', as: :business_home
  get ':id/view_available_groupsessions_embedded', to: 'businesses#view_available_groupsessions_embedded', as: :view_available_groupsessions_embedded

  get ':id/dashboard', to: 'businesses#dashboard', as: :business_dashboard
  get ':id/calendar(/:mode/:date)' => 'businesses#calendar', as: :businesses_calendar
  get ':id/get_month(/:date/:token)' => 'businesses#get_month', as: :businesses_get_month

  resources :suggestions
  resources :invoice_months

  resources :businesses, path: '/' do
    get 'edit/?tab=sessions', to: 'businesses#edit', as: :edit_sessions
    patch 'change_histories/mark_all_read', to: 'change_histories#mark_all_read', as: :mark_all_read

    resources :invoice_items,    only: [:create, :index, :new]
    resources :items
    resources :constants
    resources :taxes
    resources :memberships
    resources :reminders,    only: [:create, :index, :new]
    resources :rates, 							only: [:create]
    resources :workout_sessions
    resources :user_rates,          only: [:create, :index]
    resources :payments
  	resources :invoices

    patch    ':id/invoices/:id/pay_with_credit' => 'invoices#pay_with_credit', via: [:patch, :put], as: :invoices_pay_with_credit
    patch ':date/invoice_months/flip' => 'invoice_months#flip', via: [:patch, :put], as: :invoice_months_flip
    patch ':date/invoice_months/recalculate' => 'invoice_months#recalculate', via: [:patch, :put], as: :invoice_months_recalculate

    patch    '/users/:id/new_gdrive_workout' => 'users#new_gdrive_workout', via: [:patch, :put], as: :users_new_gdrive_workout
    get '/users/new', to: 'users#new_modal', as: :users_new_modal
    post '/users/', to: 'users#admin_create'
  	resources :users

    get '/users/:id/edit_modal', to: 'users#edit_modal', as: :users_edit_modal


    get '/login',   to: 'sessions#new'
    post '/login',   to: 'sessions#create'

    get '/embedded_login', to: 'sessions#new_embedded'
    get '/embedded_signup', to: 'users#new_embedded'
    post '/embedded_signup', to: 'users#create'
    get '/settings', to: 'users#settings'

    get '/sharks', to: 'businesses#sharks', as: :sharks #testing temporary

    get ':id/workout_sessions/add', to: 'workout_sessions#add', as: :workout_sessions_add
    get '/workout_sessions/:id/book_session(/:date)', to: 'workout_sessions#book_groupsession', as: :book_groupsession
    get '/workout_sessions/:id/cancel_session', to: 'workout_sessions#cancel_groupsession', as: :cancel_groupsession


    resources :user_workouts do
      collection do
        put :setoptions
      end
    end

    resources :user_workouts,				only: [:update, :edit]

    get '/workout_sessions/:id/view', to: 'workout_sessions#view', as: :workout_sessions_view
    patch    '/workout_sessions/:id/success' => 'workout_sessions#success', via: [:patch, :put], as: :workout_sessions_success
    patch    '/workout_sessions/:id/approve' => 'workout_sessions#approve', via: [:patch, :put], as: :workout_sessions_approve
    patch    '/workout_sessions/:id/approveallthismonth' => 'workout_sessions#approveallthismonth', via: [:patch, :put], as: :workout_sessions_approveallthismonth
    patch    '/workout_sessions/:id/approveallfollowing' => 'workout_sessions#approveallfollowing', via: [:patch, :put], as: :workout_sessions_approveallfollowing
    patch    '/workout_sessions/:id/approveupto' => 'workout_sessions#approveupto', via: [:patch, :put], as: :workout_sessions_approveupto
    patch    '/workout_sessions/:id/reschedule' => 'workout_sessions#reschedule', via: [:patch, :put], as: :workout_sessions_reschedule
    patch    '/workout_sessions/:id/cancel' => 'workout_sessions#cancel', via: [:patch, :put], as: :workout_sessions_cancel
    patch    '/workout_sessions/:id/noshow' => 'workout_sessions#noshow', via: [:patch, :put], as: :workout_sessions_noshow
    patch    '/workout_sessions/:id/remove/:date' => 'workout_sessions#remove', via: [:patch, :put], as: :workout_sessions_remove
    patch    '/workout_sessions/:id/removefollowing(/:date)' => 'workout_sessions#removefollowing', via: [:patch, :put], as: :workout_sessions_removefollowing
    patch    '/workout_sessions/:id/removeall' => 'workout_sessions#removeall', via: [:patch, :put], as: :workout_sessions_removeall
    patch    '/workout_sessions/:id/unlink' => 'workout_sessions#unlink', via: [:patch, :put], as: :workout_sessions_unlink
    patch    '/workout_sessions/:id/sync_google_event' => 'workout_sessions#sync_google_event', via: [:patch, :put], as: :workout_sessions_sync_google_event
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
	belongs_to :business
	belongs_to :tax, optional: true

	has_many :subscriptions
	has_many :users, through: :subscriptions
	has_many :invoices

	def cost_with_tax
		if cost && tax
			cost * tax.rate
		elsif cost
			cost
		else
			0
		end
	end

	def tax_amount
		if cost && tax
			cost * (tax.rate - 1)
		else
			0
		end
	end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  after_action :verify_authorized

  before_action :set_membership, only: [:show, :edit, :update, :destroy]
  before_action :set_business, only: [:new, :index, :create, :edit]
  #before_action :admin_user

  # GET /memberships
  # GET /memberships.json
  def index
    authorize @business.memberships.new
    @memberships = Membership.where(:business_id => @business)
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
    authorize @membership
  end

  # GET /memberships/new
  def new
    @membership = @business.memberships.new
    authorize @membership
  end

  # GET /memberships/1/edit
  def edit
    authorize @membership
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = @business.memberships.new(membership_params)
    authorize @membership

    respond_to do |format|
      if @membership.save
        format.html { redirect_to :back, notice: 'Membership was successfully created. ' }
        format.json { render :memberships, status: :created }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    authorize @membership

    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to business_memberships_path(@membership.business.slug), notice: 'Membership was successfully updated.' }
        format.json { render :memberships, status: :ok }
      else
        format.html { render :back }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    authorize @membership

    business = @membership.business
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to business_memberships_path(business.slug), notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_business
      @business = Business.friendly.find(params[:business_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:name, :description, :available, :cost, :tax_id, :max_workouts, :max_transfers, :available_from, :available_to)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= simple_form_for([@business, @membership]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :available %>
    <%= f.input :cost %>
    <%= f.input :tax_id, collection: Tax.where(:available => true), include_blank: "None" %>
    <%= f.input :max_workouts, label: "Max sessions" %>
    <%= f.input :max_transfers %>
    <%= f.input :available_from %>
    <%= f.input :available_to %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/memberships/_new.html.erb
<h1>New Membership</h1>

<%= simple_form_for [@business, @business.memberships.new] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :available %>
    <%= f.input :cost %>
    <%= f.input :tax_id, collection: Tax.where(:available => true), include_blank: "None" %>
    <%= f.input :max_workouts, label: "Max sessions" %>
    <%= f.input :max_transfers %>
    <%= f.input :available_from %>
    <%= f.input :available_to %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<div class="row" style="padding-bottom: 50px; padding-top: 50px;">
	<div class="col-md-6 col-md-offset-3 shdw bg-white" style="padding-bottom: 15px;">
<h1>Editing Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Back', business_memberships_path(:business_id => @membership.business.slug) %>

</br>
</br>
<% if @membership.users.any? %>
  <span class="glyphicon glyphicon-exclamation-sign rescheduled_from"></span> Can only be removed if no clients are using this membership: </br>
  <% (mu = @membership.users).each do |usr| %>
    <%= link_to usr.name, user_billing_for(usr) %>
    <% unless mu.last == usr %>
     <%= " ," %>
    <% end %>
  <% end %>
<% else %>
  <%= link_to business_membership_path(@membership.business.slug, @membership), method: :delete, data: { confirm: 'Remove membership?' }, :class=>"btn btn-danger" do %>
    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Destroy
  <% end %>
<% end %>
</div>
</div>

app/views/memberships/index.html.erb
<div class="container-fluid">
  <h1>Memberships</h1>

  <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#membership-new">
    <span class="glyphicon glyphicon-plus" style="color:#FFA07A"></span>
    <span class="btn-text">New Membership</span>
  </button>

  <div id="membership-new" class="modal fade">
    <div class="modal-dialog modal-content">
      <div class="modal-body">
        <%= render 'memberships/new' %>
      </div>
    </div>
  </div>
  <table class="table table-striped shdw" style="margin-top: 15px;">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Used by</th>
        <th>Available</th>
        <th>Cost</th>
        <th>Tax</th>
        <th>Max Sessions</th>
        <th>Max Transfers</th>
        <th>Available From</th>
        <th>Available To</th>
        <th colspan=2></th>
      </tr>
    </thead>

    <tbody>
      <% @memberships.each do |membership| %>
        <tr>
          <td><%= membership.name %></td>
          <td><%= membership.description %></td>
          <td><%= membership.users.pluck(:email) %></td>
          <td><%= membership.available %></td>
          <td><%= number_to_currency(membership.cost, :unit => "$") %></td>
          <td><%= membership.tax ? membership.tax.name : "-" %></td>
          <td><%= membership.max_workouts %></td>
          <td><%= membership.max_transfers %></td>
          <td><%= membership.available_from.strftime("%B %-d, %Y") %></td>
          <td><%= membership.available_to.strftime("%B %-d, %Y") %></td>
          <td>
              <%= link_to edit_business_membership_path(@business.slug, membership) do %>
                <span class="glyphicon glyphicon-pencil circ-btn"></span>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/memberships/new.html.erb
<div class="container-fluid" style="background-color: #F3F3F3; height: 100%;">
<h1>New Membership</h1>

<%= simple_form_for [@business, @membership] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :available %>
    <%= f.input :cost %>
    <%= f.input :tax_id, collection: Tax.where(:available => true), include_blank: "None" %>
    <%= f.input :max_workouts %>
    <%= f.input :max_transfers %>
    <%= f.input :available_from %>
    <%= f.input :available_to %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>


<%= link_to 'Back', memberships_path %>
</div>

app/views/memberships/show.html.erb
<div class="container-fluid" style="background-color: #F3F3F3; height: 100%;">
  <%= @membership.name %>
  <%= @membership.description %>
  <%= @membership.available %>

  <%= link_to 'Edit', edit_membership_path(@membership) %> |
  <%= link_to 'Back', memberships_path %>
</div>