config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "www.fitrackular.com"
  root 'businesses#welcome'

  get '/account_activations/send_activation', to: 'account_activations#send_activation', as: :account_activations_send_activation
  get '/account_activations/blacklist', to: 'account_activations#blacklist', as: :account_activations_blacklist
  get '/account_activations/:id/', to: 'account_activations#activate', :constraints => { :id => /[^\/]+/ }, as: :account_activations_activate

  resources :subscriptions
  patch 'subscribe' => 'subscriptions#subscribe', via: [:patch, :put], as: :subscriptions_subscribe
  patch 'approve' => 'subscriptions#approve', via: [:patch, :put], as: :subscriptions_approve
  patch 'unsubscribe' => 'subscriptions#unsubscribe', via: [:patch, :put], as: :subscriptions_unsubscribe
  patch 'deactivate' => 'subscriptions#deactivate', via: [:patch, :put], as: :subscriptions_deactivate

  get 'auth/failure', to: redirect('/') #Redirect to _RETRY_
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'

  get '/embedded_login', to: 'sessions#new_embedded'
  get '/embedded_signup', to: 'users#new_embedded'

  delete '/logout',  to: 'sessions#destroy'

	resources :users, except: [:index]

  get    '/settings',to: 'users#settings'
  get    '/users',to: 'users#admin_index'

  patch    '/users/:id/resync_google' => 'users#resync_google', via: [:patch, :put], as: :users_resync_google
	patch    '/users/:id/approve' => 'users#approve', via: [:patch, :put], as: :users_approve

  resources :friends, 						only: [:create, :destroy]
  patch    '/friends/:id/approve' => 'friends#approve', via: [:patch, :put], as: :friends_approve

  get 'auth/:provider/callback', to: 'sessions#google_authorize'

  resources :reminders
  get ':id/reminders/:id/add', to: 'reminders#add', as: :reminders_add
  get 'reminders/:id/view', to: 'reminders#view', as: :reminders_view

  resources :invoice_items
  resources :user_rates

  patch    ':id/invoices/:id/set_processed' => 'invoices#set_processed', via: [:patch, :put], as: :invoices_set_processed
  patch    ':id/invoices/:id/set_unprocessed' => 'invoices#set_unprocessed', via: [:patch, :put], as: :invoices_set_unprocessed
  patch    ':id/invoices/:id/settle_month' => 'invoices#settle_month', via: [:patch, :put], as: :invoices_settle_month
  patch ':id/invoices/:id/reconcile' => 'invoices#reconcile', via: [:patch, :put], as: :invoices_reconcile

  get ':id/home', to: 'businesses#home', as: :business_home
  get ':id/view_available_groupsessions_embedded', to: 'businesses#view_available_groupsessions_embedded', as: :view_available_groupsessions_embedded

  get ':id/dashboard', to: 'businesses#dashboard', as: :business_dashboard
  get ':id/calendar(/:mode/:date)' => 'businesses#calendar', as: :businesses_calendar
  get ':id/get_month(/:date/:token)' => 'businesses#get_month', as: :businesses_get_month

  resources :suggestions
  resources :invoice_months

  resources :businesses, path: '/' do
    get 'edit/?tab=sessions', to: 'businesses#edit', as: :edit_sessions
    patch 'change_histories/mark_all_read', to: 'change_histories#mark_all_read', as: :mark_all_read

    resources :invoice_items,    only: [:create, :index, :new]
    resources :items
    resources :constants
    resources :taxes
    resources :memberships
    resources :reminders,    only: [:create, :index, :new]
    resources :rates, 							only: [:create]
    resources :workout_sessions
    resources :user_rates,          only: [:create, :index]
    resources :payments
  	resources :invoices

    patch    ':id/invoices/:id/pay_with_credit' => 'invoices#pay_with_credit', via: [:patch, :put], as: :invoices_pay_with_credit
    patch ':date/invoice_months/flip' => 'invoice_months#flip', via: [:patch, :put], as: :invoice_months_flip
    patch ':date/invoice_months/recalculate' => 'invoice_months#recalculate', via: [:patch, :put], as: :invoice_months_recalculate

    patch    '/users/:id/new_gdrive_workout' => 'users#new_gdrive_workout', via: [:patch, :put], as: :users_new_gdrive_workout
    get '/users/new', to: 'users#new_modal', as: :users_new_modal
    post '/users/', to: 'users#admin_create'
  	resources :users

    get '/users/:id/edit_modal', to: 'users#edit_modal', as: :users_edit_modal


    get '/login',   to: 'sessions#new'
    post '/login',   to: 'sessions#create'

    get '/embedded_login', to: 'sessions#new_embedded'
    get '/embedded_signup', to: 'users#new_embedded'
    post '/embedded_signup', to: 'users#create'
    get '/settings', to: 'users#settings'

    get '/sharks', to: 'businesses#sharks', as: :sharks #testing temporary

    get ':id/workout_sessions/add', to: 'workout_sessions#add', as: :workout_sessions_add
    get '/workout_sessions/:id/book_session(/:date)', to: 'workout_sessions#book_groupsession', as: :book_groupsession
    get '/workout_sessions/:id/cancel_session', to: 'workout_sessions#cancel_groupsession', as: :cancel_groupsession


    resources :user_workouts do
      collection do
        put :setoptions
      end
    end

    resources :user_workouts,				only: [:update, :edit]

    get '/workout_sessions/:id/view', to: 'workout_sessions#view', as: :workout_sessions_view
    patch    '/workout_sessions/:id/success' => 'workout_sessions#success', via: [:patch, :put], as: :workout_sessions_success
    patch    '/workout_sessions/:id/approve' => 'workout_sessions#approve', via: [:patch, :put], as: :workout_sessions_approve
    patch    '/workout_sessions/:id/approveallthismonth' => 'workout_sessions#approveallthismonth', via: [:patch, :put], as: :workout_sessions_approveallthismonth
    patch    '/workout_sessions/:id/approveallfollowing' => 'workout_sessions#approveallfollowing', via: [:patch, :put], as: :workout_sessions_approveallfollowing
    patch    '/workout_sessions/:id/approveupto' => 'workout_sessions#approveupto', via: [:patch, :put], as: :workout_sessions_approveupto
    patch    '/workout_sessions/:id/reschedule' => 'workout_sessions#reschedule', via: [:patch, :put], as: :workout_sessions_reschedule
    patch    '/workout_sessions/:id/cancel' => 'workout_sessions#cancel', via: [:patch, :put], as: :workout_sessions_cancel
    patch    '/workout_sessions/:id/noshow' => 'workout_sessions#noshow', via: [:patch, :put], as: :workout_sessions_noshow
    patch    '/workout_sessions/:id/remove/:date' => 'workout_sessions#remove', via: [:patch, :put], as: :workout_sessions_remove
    patch    '/workout_sessions/:id/removefollowing(/:date)' => 'workout_sessions#removefollowing', via: [:patch, :put], as: :workout_sessions_removefollowing
    patch    '/workout_sessions/:id/removeall' => 'workout_sessions#removeall', via: [:patch, :put], as: :workout_sessions_removeall
    patch    '/workout_sessions/:id/unlink' => 'workout_sessions#unlink', via: [:patch, :put], as: :workout_sessions_unlink
    patch    '/workout_sessions/:id/sync_google_event' => 'workout_sessions#sync_google_event', via: [:patch, :put], as: :workout_sessions_sync_google_event
  end
end

app/helpers/workout_sessions_helper.rb
module WorkoutSessionsHelper
	def nl2br(s)
	  s.gsub(/\n/, '<br>')
	end

	def render_view_for(event, event_new, date, user)
		if event.business.view_as_employee?(user)
			case event.eventtype
			when WorkoutSession.workout
				puts "workout admin"
				return render 'session_workout_admin', ws: event, ws_new: event_new
			when WorkoutSession.event
				puts "event admin"
				return render 'session_event', ws: event
			when WorkoutSession.groupworkout
				puts "instance group admin"
				return render 'session_groupworkout_admin', ws: event
			when -WorkoutSession.groupworkout
				puts "repeating group admin"
				return render 'session_repeating_groupworkout_admin', ws: event
			end
		else
			case event.eventtype
			when WorkoutSession.workout
				puts "workout client"
				return render 'session_workout_client', ws: event, ws_new: event_new
			when WorkoutSession.event
				puts "event client"
				#return render 'session_event', ws: event
			when WorkoutSession.groupworkout
				puts "group client"
				return render 'session_groupworkout_client', ws: event
			when -WorkoutSession.groupworkout
				puts "repeating group client"
				return render 'session_repeating_groupworkout_client', ws: event
			end
		end
	end

	def paid_status(ws)
		if ws.paid?
			return "Paid"
		else
			return "Unpaid"
		end
	end

  def is_groupworkout_and_in_futuredate_or_partakes_in(event, partakes_in_hash, date = nil)
		if event.eventtype == WorkoutSession.groupworkout && (event.date > Time.zone.now || partakes_in_hash.key?(event.id))
			return true
		elsif event.eventtype == -WorkoutSession.groupworkout && (date > Time.zone.now || partakes_in_hash.key?(event.id))
			return true
		end
		return false
  end

	def date_for(w)
		"<span class='event_header_day'>" + w.date.strftime("%A").upcase + "</span> </br> " + w.date.strftime("<span class='event_header_date'> %B %-d, %Y at %-I:%M%p</span>")
	end

  def date_for_old(w)
    w.date.strftime("%A %B %-d, %Y")
	end

	def date_time_for(w)
		start_date = w.date
		start_date.strftime("%B %-d, %Y @ %I:%M%P")
	end

	def buffer_time_for(w)
		w.bfr_from.to_s + ' min <span class="glyphicon glyphicon-transfer" aria-hidden="true"></span> ' + w.bfr_to.to_s + " min"
	end

	def date_until(w)
		if Time.zone.now.to_date == w.date.to_date
			"Today"
		elsif Time.zone.now.to_date < w.date.to_date
			d = (w.date.to_date - Time.zone.today.to_date).to_i
			"Coming up in " + pluralize(d, "day")
		else
			d = (Time.zone.now.to_date - w.date.to_date ).to_i
			pluralize(d, "day") + " ago"
		end
	end

	def assigned_clients(w)
		clients = UserWorkout.where(:workout_session_id => w.id)
		temp = []
		clients.each do |c|
			temp << c.user_id
		end

		temp
	end

	def can_edit(ws)
		if current_user.admin
			true
		elsif [0,4].include?(ws.status) && (ws.date > Time.zone.now + 1.days)
			true
		else
			false
		end
	end

	def edit_status(ws)
		if can_edit(ws)
			"<span class='glyphicon success glyphicon-ok-sign'></span>"
		else
			"<span class='glyphicon noshow glyphicon-exclamation-sign'></span>"
		end
	end
end

app/views/workout_sessions/_book_groupsession.html.erb
<div class="modal-dialog">

  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title"> Find your perfect time to train! </h4>
    </div>
    <div class="modal-body">

      TESTING!

    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>

</div>

app/views/workout_sessions/_cancel.html.erb
<% unless !current_user.admin? || @workout_session.status == 3 || @workout_session.status == 2 %>			
	<%= link_to "Cancel", workout_sessions_cancel_path(:id => @workout_session.id), method: :patch, :class=>"btn btn-default" %>
<% end %>

app/views/workout_sessions/_session_groupworkout_admin.html.erb
<%= simple_form_for([@business, ws], :class => "addWorkoutForm") do |f| %>
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title"><%= raw(date_for(ws)) %></h4>
			<%= raw(workout_status(ws, nil, true)) %>

			<div class="dropdown" style="display: inline-block;">
				<button style=" border: none; background: none; padding-left:2px; padding-right:2px; " id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
	        <span class="glyphicon glyphicon-cog event-cog" aria-hidden="true"></span>
	      </button>

		      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
		        <li>
		          <%= link_to reminders_add_path(ws), remote: true, 'data-toggle' => 'modal', 'data-target' => "#reminders-view" do %>
		          Add reminder
		        <% end %>
		        </li>
		        <li class="divider", id: "headertext" ></li>
		      <% if ws.status != WorkoutSession::STATUS["draft"] %>
		        <% unless ws.status == WorkoutSession::STATUS["ok"] %>
		          <% lbl = (Date.today > ws.date) ? "Success" : "Upcoming" %>
		          <li>
		          <%= link_to lbl, business_workout_sessions_success_path(@business.slug, ws), method: :patch %>
		          </li>
		        <% end %>

		        <% unless ws.status == WorkoutSession::STATUS["noshow"] %>
		          <li>	<!-- No show -->
		            <%= link_to "No show", business_workout_sessions_noshow_path(@business.slug, ws), method: :patch %>
		          </li>
		        <% end %>

		        <% unless ws.status == WorkoutSession::STATUS["cancel"] %>
		          <li>	<!-- Cancel -->
		            <%= link_to "Cancel", business_workout_sessions_cancel_path(@business.slug, ws), method: :patch %>
		          </li>
		        <% end %>
		      <% else %>
		        <% unless ws.status == WorkoutSession::STATUS["ok"] %>
		          <li>
		            <%= link_to "Approve", business_workout_sessions_approve_path(@business.slug, ws), method: :patch %>
		          </li>
		          <li>
		            <%= link_to "Approve up to", business_workout_sessions_approveupto_path(@business.slug, ws), method: :patch %>
		          </li>
		          <li>
		            <%= link_to "Approve following", business_workout_sessions_approveallfollowing_path(@business.slug, ws), method: :patch %>
		          </li>
		          <li>
		            <%= link_to "Approve all this month", business_workout_sessions_approveallthismonth_path(@business.slug, ws), method: :patch %>
		          </li>
		        <% end %>
		      <% end %>
		        <li class="divider", id: "headertext" ></li>
		        <li><%= link_to "Remove", business_workout_session_path(@business.slug, ws), method: :delete,
		                data: { confirm: "Remove session?" } %></li>
		        <li><%= link_to "Remove following sessions", business_workout_sessions_removefollowing_path(@business.slug, ws), method: :patch,
		                data: { confirm: "Remove following sessions?" } %></li>
		        <li><%= link_to "Remove all sessions", business_workout_sessions_removeall_path(@business.slug, ws), method: :patch,
		                data: { confirm: "Remove all sessions?" } %></li>
		      </ul>
	    </div>
			<%= render 'session_tags', ws: ws %>
	</div>

	<%= render 'shared/error_messages', object: f.object %>
	<section class="event_time" style="padding-top: 10px; padding-left:40px; padding-right: 40px;">
		<div >
			<div>
				<span class="glyphicon glyphicon-time event-icons"></span>
				<label class="label_plain">From</label>
			</div>

			<div class="form-inline event_from">
					<%= f.input :date, as: :string, label: false, input_html: { id: "datetimepicker_start_admin_modal", value: ws.date.strftime('%m-%d-%Y %I:%M %p')} %>
					<%= f.input :bfr_from, label: false, :include_hidden => false, :include_blank => false, collection: { "no buffer" => 0, "15 minutes" => 15, "30 minutes" => 30, "45 minutes" =>45, "60 minutes" => 60}, selected: ws.bfr_from %>
			</div>

			<div>
				<label class="label_plain">To</label>
			</div>
			<div class="form-inline event_to">
				<%= f.input :duration, as: :string, label: false, input_html: { id: "datetimepicker_end_admin_modal", value: (ws.date + 1.hour).strftime('%m-%d-%Y %I:%M %p')} %>
				<%= f.input :bfr_to, label: false, :include_hidden => false, :include_blank => false, collection: { "no buffer" => 0, "15 minutes" => 15, "30 minutes" => 30, "45 minutes" =>45, "60 minutes" => 60}, selected: ws.bfr_to %>
			</div>
		</div>
	</section>

	<section class="event_title">
		<span class="glyphicon glyphicon-flag event-icons"></span>
		<label class="label_plain">What</label>
		<%= f.input :title, label: false, :placeholder => "Enter a title.." %>
	</section>

	<section class="event_location" style="padding-left:40px; padding-right: 40px;">
		<span class="glyphicon glyphicon-map-marker event-icons"></span>
		<label class="label_plain">Where</label>
		<%= f.input :location, label: false, :placeholder => "Enter a location..", input_html: { value: ws.location } %>
	</section>

	<section class="event-clients" style="padding: 0px 40px 10px 40px;">
		<div>
			<span class="glyphicon glyphicon-user event-icons"></span>
			<label class="label_plain">Who</label>
		</div>
		<%= f.collection_select :clients, User.all, :id, :name, {include_hidden: false, selected: (assigned_clients ws)}, { multiple: true, class: 'userselect2', style: "width: 100%; height: 100%;"} %>
	</section>

	<section class="event-memo" style="padding: 0px 40px 10px 40px;">
		<div>
			<span class="glyphicon glyphicon-comment event-icons"></span>
			<label class="label_plain">Memo</label>
		</div>

		<%= f.input :memo, label: false, as: :text, autofocus: true, :placeholder => "Write a memo..", :input_html => {:style => 'width: 100%', :rows => 5, class: 'response-project', value: ws.memo} %>
	</section>

	<div class="modal-footer">
    <%= f.hidden_field :eventtype, :value => WorkoutSession.groupworkout %>
   	<%= hidden_field_tag(:old_id, ws.id.to_s) %>
		<div class="col-md-4"></div>
		<div class="col-md-4"></div>
		<div class="col-md-4">
			<% if ws.group %>
			<div class="btn-group" style="width: 100%;">
				<button type="button" class="btn btn-success dropdown-toggle" style="width: 100%;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Save <span class="caret"></span>
				</button>
				<ul class="dropdown-menu">
					<li><%= f.submit "This event only" %></li>
					<li> <hr style="margin-bottom: 8px; margin-top: 8px;"> </li>
					<li><%= f.submit "All future events" %></li>
					<li><%= f.submit "All events" %></li>
				</ul>
			</div>
			<% else %>
				<%= f.submit "Save", class: "btn btn-success" %>
			<% end %>
		</div>
  </div>

	</div>
<% end %>

<script>
	$('.userselect2').select2({
			placeholder: "Select clients..",
			closeOnSelect: false,
			allowClear: true
		});

	$('#datetimepicker_start_admin_modal').datetimepicker({
			sideBySide: true,
			stepping: 15
		});

	$('#datetimepicker_end_admin_modal').datetimepicker({
			sideBySide: true,
			stepping: 15
		});

	$("#datetimepicker_start_admin_modal").on("dp.change", function (e) {
			var date = e.date.clone();
			date.add(1, 'hours');

			$('#datetimepicker_end_admin_modal').data("DateTimePicker").minDate(e.date);
			$('#datetimepicker_end_admin_modal').data("DateTimePicker").date(date);
		});

	$("#event-repeat-toggle").hide();
  $("a#toggle_repeat").click(function(event){
    event.preventDefault();
    $("#event-repeat-toggle").toggle();

		$('.check_days').prop("checked", false);
  });
</script>

app/views/workout_sessions/_session_repeating_groupworkout_admin.html.erb
<%= simple_form_for([@business, @ws_new], :class => "addWorkoutForm") do |f| %>
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title"><%= raw(date_for(@ws_new)) %></h4>
			<%= raw(repeat_groupworkout_status(ws, @ws_new.date, true)) %>
			<div class="dropdown" style="display: inline-block;">
				<button style=" border: none; background: none; padding-left:2px; padding-right:2px; " id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
					<span class="glyphicon glyphicon-cog event-cog" aria-hidden="true"></span>
				</button>

				<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
					<li>
						<%= link_to reminders_add_path(ws), remote: true, 'data-toggle' => 'modal', 'data-target' => "#reminders-view" do %>
						Add reminder
						<% end %>
					</li>
					<li class="divider", id: "headertext" ></li>
					<% if ws.status != WorkoutSession::STATUS["draft"] %>
					<% unless ws.status == WorkoutSession::STATUS["ok"] %>
					<% lbl = (Time.zone.now.today > ws.date) ? "Success" : "Upcoming" %>
					<li>
						<%= link_to lbl, business_workout_sessions_success_path(@business.id, ws), method: :patch %>
					</li>
					<% end %>

					<% unless ws.status == WorkoutSession::STATUS["cancel"] %>
					<li>	<!-- Cancel -->
						<%= link_to "Cancel", business_workout_sessions_cancel_path(@business.slug, ws), method: :patch %>
					</li>
					<% end %>
					<% end %>
					<li class="divider", id: "headertext" ></li>
					<li><%= link_to "Remove this session", business_workout_sessions_remove_path(@business.slug, ws, ws.date.strftime("%m/%d/%Y")), method: :patch,
					data: { confirm: "Remove session?" } %></li>
					<li><%= link_to "Remove following sessions", business_workout_sessions_removefollowing_path(@business.slug, ws, ws.date.strftime("%m/%d/%Y")), method: :patch,
					data: { confirm: "Remove following sessions?" } %></li>
					<li><%= link_to "Remove all sessions", business_workout_sessions_removeall_path(@business.slug, ws), method: :patch,
					data: { confirm: "Remove all sessions?" } %></li>
				</ul>
			</div>

			<%= render 'session_tags', ws: ws %>

			<div>
				<small> <span class="glyphicon glyphicon-repeat" style="padding-right: 2px; margin-left: 1px;"></span> Repeat: <a href="#"> Ends never.. </a> </small>
				<% if ws.group %>
					<small> on <a href="#"> <%= repeat_on_to_weekdays ws.group.repeat_on %> </a> </small>
				<% end %>
			</div>

	</div>

	<%= render 'shared/error_messages', object: f.object %>
	<section class="event_time" style="padding-top: 10px; padding-left:40px; padding-right: 40px;">
		<div >
			<div>
				<span class="glyphicon glyphicon-time event-icons"></span>
				<label class="label_plain">From</label>
			</div>

			<div class="form-inline event_from">
					<%= f.input :date, as: :string, label: false, input_html: { id: "datetimepicker_start_admin_modal", value: @ws_new.date.strftime('%m-%d-%Y %I:%M %p')} %>
					<%= f.input :bfr_from, label: false, :include_hidden => false, :include_blank => false, collection: { "no buffer" => 0, "15 minutes" => 15, "30 minutes" => 30, "45 minutes" =>45, "60 minutes" => 60}, selected: ws.bfr_from %>
			</div>

			<div>
				<label class="label_plain">To</label>
			</div>
			<div class="form-inline event_to">
				<%= f.input :duration, as: :string, label: false, input_html: { id: "datetimepicker_end_admin_modal", value: (@ws_new.date + 1.hour).strftime('%m-%d-%Y %I:%M %p')} %>
				<%= f.input :bfr_to, label: false, :include_hidden => false, :include_blank => false, collection: { "no buffer" => 0, "15 minutes" => 15, "30 minutes" => 30, "45 minutes" =>45, "60 minutes" => 60}, selected: ws.bfr_to %>
			</div>
		</div>
	</section>

	<section class="event_title">
		<span class="glyphicon glyphicon-flag event-icons"></span>
		<label class="label_plain">What</label>
		<%= f.input :title, label: false, :placeholder => "Enter a title..", input_html: { value: ws.title } %>
	</section>

	<section class="event_location" style="padding-left:40px; padding-right: 40px;">
		<span class="glyphicon glyphicon-map-marker event-icons"></span>
		<label class="label_plain">Where</label>
		<%= f.input :location, label: false, :placeholder => "Enter a location..", input_html: { value: ws.location } %>
	</section>

	<section class="event-clients" style="padding: 0px 40px 10px 40px;">
		<div>
			<span class="glyphicon glyphicon-user event-icons"></span>
			<label class="label_plain">Who</label>
		</div>
		<%= f.collection_select :clients, User.all, :id, :name, {include_hidden: false, selected: (assigned_clients ws)}, { multiple: true, class: 'userselect2', style: "width: 100%; height: 100%;"} %>
	</section>

	<section class="event-memo" style="padding: 0px 40px 10px 40px;">
		<div>
			<span class="glyphicon glyphicon-comment event-icons"></span>
			<label class="label_plain">Memo</label>
		</div>

		<%= f.input :memo, label: false, as: :text, autofocus: true, :placeholder => "Write a memo..", :input_html => {:style => 'width: 100%', :rows => 5, class: 'response-project', value: ws.memo} %>
	</section>

	<div class="modal-footer">
    <%= f.hidden_field :eventtype, :value => WorkoutSession.groupworkout %>
		<%= f.hidden_field :group_id, :value => @ws.group_id %>
   	<%= hidden_field_tag(:old_id, ws.id.to_s) %>
		<%= hidden_field_tag(:old_date, @ws_new.date.strftime("%m/%d/%Y")) %>
    <div class="col-md-4 sm-mrgn-wrkt float-right">
			<!-- Single button -->
			<div class="btn-group col-md-4" style="width: 100%;">
			  <button type="button" class="btn btn-success dropdown-toggle" style="width: 100%;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    Save <span class="caret"></span>
			  </button>
			  <ul class="dropdown-menu">
			    <li><%= f.submit "This event only" %></li>
					<li> <hr style="margin-bottom: 8px; margin-top: 8px;"> </li>
			    <li><%= f.submit "All future events" %></li>
			    <li><%= f.submit "All events" %></li>
			  </ul>
			</div>
		</div>
  </div>

	</div>
<% end %>

<script>
	$('.userselect2').select2({
			placeholder: "Select clients..",
			closeOnSelect: false,
			allowClear: true
		});

	$('#datetimepicker_start_admin_modal').datetimepicker({
			sideBySide: true,
			stepping: 15
		});



	$('#datetimepicker_end_admin_modal').datetimepicker({
			sideBySide: true,
			stepping: 15
		});

	$("#datetimepicker_start_admin_modal").on("dp.change", function (e) {
			var date = e.date.clone();
			date.add(1, 'hours');

			$('#datetimepicker_end_admin_modal').data("DateTimePicker").minDate(e.date);
			$('#datetimepicker_end_admin_modal').data("DateTimePicker").date(date);
		});

	$("#event-repeat-toggle").hide();
  $("a#toggle_repeat").click(function(event){
    event.preventDefault();
    $("#event-repeat-toggle").toggle();

		$('.check_days').prop("checked", false);
  });
</script>

app/views/workout_sessions/_session_tags.html.erb
<div class="session-tags">
  <span class="label tag-default"> <%= WorkoutSession.eventtype_string(ws.eventtype) %> </span>
  &nbsp;

  <% if ws.billable_eventtype? %>
    <span class="label tag-default"> <%= paid_status(ws) %> </span>
  <% end %>
</div>

app/views/workout_sessions/_view.html.erb
<%= render_view_for(@ws, @ws_new, @date, current_user) %>

app/views/workout_sessions/add.js.erb
 $("#show-workout-modal").html("<%= escape_javascript(render partial: 'workout_sessions/add', locals: {ws: @ws}) %>")

app/views/workout_sessions/book_groupsession.js.erb
$("#viewGroupSessionsModal").html("<%= escape_javascript(render partial: 'book_groupsession') %>");