config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "www.fitrackular.com"
  root 'businesses#welcome'

  get '/account_activations/send_activation', to: 'account_activations#send_activation', as: :account_activations_send_activation
  get '/account_activations/blacklist', to: 'account_activations#blacklist', as: :account_activations_blacklist
  get '/account_activations/:id/', to: 'account_activations#activate', :constraints => { :id => /[^\/]+/ }, as: :account_activations_activate

  resources :subscriptions
  patch 'subscribe' => 'subscriptions#subscribe', via: [:patch, :put], as: :subscriptions_subscribe
  patch 'approve' => 'subscriptions#approve', via: [:patch, :put], as: :subscriptions_approve
  patch 'unsubscribe' => 'subscriptions#unsubscribe', via: [:patch, :put], as: :subscriptions_unsubscribe
  patch 'deactivate' => 'subscriptions#deactivate', via: [:patch, :put], as: :subscriptions_deactivate

  get 'auth/failure', to: redirect('/') #Redirect to _RETRY_
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'

  get '/embedded_login', to: 'sessions#new_embedded'
  get '/embedded_signup', to: 'users#new_embedded'

  delete '/logout',  to: 'sessions#destroy'

	resources :users, except: [:index]

  get    '/settings',to: 'users#settings'
  get    '/users',to: 'users#admin_index'

  patch    '/users/:id/resync_google' => 'users#resync_google', via: [:patch, :put], as: :users_resync_google
	patch    '/users/:id/approve' => 'users#approve', via: [:patch, :put], as: :users_approve

  resources :friends, 						only: [:create, :destroy]
  patch    '/friends/:id/approve' => 'friends#approve', via: [:patch, :put], as: :friends_approve

  get 'auth/:provider/callback', to: 'sessions#google_authorize'

  resources :reminders
  get ':id/reminders/:id/add', to: 'reminders#add', as: :reminders_add
  get 'reminders/:id/view', to: 'reminders#view', as: :reminders_view

  resources :invoice_items
  resources :user_rates

  patch    ':id/invoices/:id/set_processed' => 'invoices#set_processed', via: [:patch, :put], as: :invoices_set_processed
  patch    ':id/invoices/:id/set_unprocessed' => 'invoices#set_unprocessed', via: [:patch, :put], as: :invoices_set_unprocessed
  patch    ':id/invoices/:id/settle_month' => 'invoices#settle_month', via: [:patch, :put], as: :invoices_settle_month
  patch ':id/invoices/:id/reconcile' => 'invoices#reconcile', via: [:patch, :put], as: :invoices_reconcile

  get ':id/home', to: 'businesses#home', as: :business_home
  get ':id/view_available_groupsessions_embedded', to: 'businesses#view_available_groupsessions_embedded', as: :view_available_groupsessions_embedded

  get ':id/dashboard', to: 'businesses#dashboard', as: :business_dashboard
  get ':id/calendar(/:mode/:date)' => 'businesses#calendar', as: :businesses_calendar
  get ':id/get_month(/:date/:token)' => 'businesses#get_month', as: :businesses_get_month

  resources :suggestions
  resources :invoice_months

  resources :businesses, path: '/' do
    get 'edit/?tab=sessions', to: 'businesses#edit', as: :edit_sessions
    patch 'change_histories/mark_all_read', to: 'change_histories#mark_all_read', as: :mark_all_read

    resources :invoice_items,    only: [:create, :index, :new]
    resources :items
    resources :constants
    resources :taxes
    resources :memberships
    resources :reminders,    only: [:create, :index, :new]
    resources :rates, 							only: [:create]
    resources :workout_sessions
    resources :user_rates,          only: [:create, :index]
    resources :payments
  	resources :invoices

    patch    ':id/invoices/:id/pay_with_credit' => 'invoices#pay_with_credit', via: [:patch, :put], as: :invoices_pay_with_credit
    patch ':date/invoice_months/flip' => 'invoice_months#flip', via: [:patch, :put], as: :invoice_months_flip
    patch ':date/invoice_months/recalculate' => 'invoice_months#recalculate', via: [:patch, :put], as: :invoice_months_recalculate

    patch    '/users/:id/new_gdrive_workout' => 'users#new_gdrive_workout', via: [:patch, :put], as: :users_new_gdrive_workout
    get '/users/new', to: 'users#new_modal', as: :users_new_modal
    post '/users/', to: 'users#admin_create'
  	resources :users

    get '/users/:id/edit_modal', to: 'users#edit_modal', as: :users_edit_modal


    get '/login',   to: 'sessions#new'
    post '/login',   to: 'sessions#create'

    get '/embedded_login', to: 'sessions#new_embedded'
    get '/embedded_signup', to: 'users#new_embedded'
    post '/embedded_signup', to: 'users#create'
    get '/settings', to: 'users#settings'

    get '/sharks', to: 'businesses#sharks', as: :sharks #testing temporary

    get ':id/workout_sessions/add', to: 'workout_sessions#add', as: :workout_sessions_add
    get '/workout_sessions/:id/book_session(/:date)', to: 'workout_sessions#book_groupsession', as: :book_groupsession
    get '/workout_sessions/:id/cancel_session', to: 'workout_sessions#cancel_groupsession', as: :cancel_groupsession


    resources :user_workouts do
      collection do
        put :setoptions
      end
    end

    resources :user_workouts,				only: [:update, :edit]

    get '/workout_sessions/:id/view', to: 'workout_sessions#view', as: :workout_sessions_view
    patch    '/workout_sessions/:id/success' => 'workout_sessions#success', via: [:patch, :put], as: :workout_sessions_success
    patch    '/workout_sessions/:id/approve' => 'workout_sessions#approve', via: [:patch, :put], as: :workout_sessions_approve
    patch    '/workout_sessions/:id/approveallthismonth' => 'workout_sessions#approveallthismonth', via: [:patch, :put], as: :workout_sessions_approveallthismonth
    patch    '/workout_sessions/:id/approveallfollowing' => 'workout_sessions#approveallfollowing', via: [:patch, :put], as: :workout_sessions_approveallfollowing
    patch    '/workout_sessions/:id/approveupto' => 'workout_sessions#approveupto', via: [:patch, :put], as: :workout_sessions_approveupto
    patch    '/workout_sessions/:id/reschedule' => 'workout_sessions#reschedule', via: [:patch, :put], as: :workout_sessions_reschedule
    patch    '/workout_sessions/:id/cancel' => 'workout_sessions#cancel', via: [:patch, :put], as: :workout_sessions_cancel
    patch    '/workout_sessions/:id/noshow' => 'workout_sessions#noshow', via: [:patch, :put], as: :workout_sessions_noshow
    patch    '/workout_sessions/:id/remove/:date' => 'workout_sessions#remove', via: [:patch, :put], as: :workout_sessions_remove
    patch    '/workout_sessions/:id/removefollowing(/:date)' => 'workout_sessions#removefollowing', via: [:patch, :put], as: :workout_sessions_removefollowing
    patch    '/workout_sessions/:id/removeall' => 'workout_sessions#removeall', via: [:patch, :put], as: :workout_sessions_removeall
    patch    '/workout_sessions/:id/unlink' => 'workout_sessions#unlink', via: [:patch, :put], as: :workout_sessions_unlink
    patch    '/workout_sessions/:id/sync_google_event' => 'workout_sessions#sync_google_event', via: [:patch, :put], as: :workout_sessions_sync_google_event
  end
end

app/models/business.rb
class Business < ApplicationRecord
	extend FriendlyId
	friendly_id :name, use: :slugged

	after_validation :move_friendly_id_error_to_name

	belongs_to :user, optional: true

	has_many :constants #
	has_many :groups #
	has_many :invoices #
	has_many :business_users
	has_many :items #
	has_many :invoice_items #
	has_many :invoice_months
	has_many :memberships #
	has_many :payments #
	has_many :reminders #
	has_many :reschedules #
	has_many :taxes #
	has_many :user_rates #
	has_many :workout_sessions #
	has_many :user_workouts
	has_many :change_histories

	has_many :subscriptions
	has_many :users, :through => :subscriptions

	mount_uploader :avatar, AvatarUploader

	update_interval = Time.zone.now - 15.minutes

	BOOK_TYPES = ['Private Session', 'Group Session']
	EVENING_NOTIFICATIONS_TIME = Time.zone.now.end_of_day..(Time.zone.now.end_of_day + 12.hours + 30.minutes)
	MORNING_NOTIFICATIONS_TIME = (Time.zone.now.beginning_of_day + 12.days + 30.minutes)..Time.zone.now.end_of_day

	def send_booking_notifications
		changes = change_histories.where(notified_email: false).where.not(user: get_employees)
		changes.update_all(notified_email: true)
		if changes.any?
			ApplicationMailer.booking_notification_email(self, changes).deliver
		else
			puts "No changes to mail"
		end
	end

	def send_evening_notifications
		send_session_notification(Business::EVENING_NOTIFICATIONS_TIME)
	end

	def send_morning_notifications
		send_session_notification(Business::MORNING_NOTIFICATIONS_TIME)
	end

	def send_session_notification(date_range)
		notification_workouts = grouped_by_client_workouts_for_date_range(date_range)

		puts "Number of notifications #{ notification_workouts.count }"
		notification_workouts.each do |client, client_user_workouts|
			ApplicationMailer.send_workouts_reminder(client, client_user_workouts).deliver if client.email_session_reminder && client.activated
		end
	end

	def allow_group_session?
		return true if session_type.blank?
		if session_type[1] == "1"
			return true
		end

		false
	end

	def allow_private_session?
		return true if session_type.blank?
		if session_type[0] == "1"
			return true
		end

		false
	end

	def grouped_by_client_workouts_for_date_range(date_range)
		UserWorkout.joins(:workout_session)
		.where(workout_sessions: {date: date_range, eventtype: WorkoutSession.billable_eventtype, status: WorkoutSession.upcoming, business_id: id})
		.group_by(&:user)
	end

	def pending_users
		User.joins("INNER JOIN subscriptions ON (#{id} = subscriptions.business_id AND users.id = subscriptions.user_id)")
		.where(subscriptions: {:active => true}).where(subscriptions: {:status => Subscription.status_pending})
		.joins("LEFT JOIN profiles ON users.id = profiles.user_id").reorder("profiles.firstname")
	end

	def active_users_all
		User.joins("INNER JOIN subscriptions ON (#{id} = subscriptions.business_id AND users.id = subscriptions.user_id)")
		.where(subscriptions: {:status => Subscription.status_subscribed}).joins("LEFT JOIN profiles ON users.id = profiles.user_id")
		.reorder("profiles.firstname")
	end

	def subscribed_users
		User.joins("INNER JOIN subscriptions ON (#{id} = subscriptions.business_id AND users.id = subscriptions.user_id)")
		.where(subscriptions: {:status => Subscription.status_subscribed})
	end

	def active_users
		User.get_active_clients(nil, self).joins("INNER JOIN subscriptions ON (#{id} = subscriptions.business_id AND users.id = subscriptions.user_id)")
		.where(subscriptions: {:status => Subscription.status_subscribed}).joins("LEFT JOIN profiles ON users.id = profiles.user_id")
		.reorder("profiles.firstname")
	end

	def inactive_users
		User.get_inactive_clients(nil, self).joins("INNER JOIN subscriptions ON (#{id} = subscriptions.business_id AND users.id = subscriptions.user_id)")
		.where(subscriptions: {:status => Subscription.status_subscribed}).joins("LEFT JOIN profiles ON users.id = profiles.user_id")
		.reorder("profiles.firstname")
	end

	def deactivated_users
		User.joins("INNER JOIN subscriptions ON (#{id} = subscriptions.business_id AND users.id = subscriptions.user_id)")
		.where(subscriptions: {:status => [Subscription.status_unsubscribed, Subscription.status_deactivated]})
		.joins("LEFT JOIN profiles ON users.id = profiles.user_id").reorder("profiles.firstname")
	end

	def get_subscription (user_id)
		subscriptions.where(:user_id => user_id, :business_id => id).first
	end

	def subscribed_user?(user_id)
		Subscription.active_subscription?(user_id, id)
	end

	def view_as_employee?(usr)
		is_owner?(usr.id) || is_employee?(usr.id) || usr.admin?
	end

	def owner
		user
	end

	def get_employees
 		owner
	end

	def get_session_type
		if session_type.blank?
			return "0" * BOOK_TYPES.length
		end
		session_type
	end

	def is_employee?(user_id)
		subscriptions.where(role: :employee, active: true, user_id: user_id).any?
	end

	def is_owner?(usr_id)
		user_id == usr_id
	end

	def set_owner(usr: )
		user = usr
	end

	def move_friendly_id_error_to_name
		errors.add :name, *errors.delete(:friendly_id) if errors[:friendly_id].present?
	end

	def default_workout_sessions_tax
		@default_workout_sessions_tax ||= Constant.default_workout_sessions_tax self
	end

	def default_memberships_tax
		@default_memberships_tax ||= Constant.default_membership_tax self
	end
end

app/views/notifications/_notifications.html.erb
<% event_changes = ChangeHistory.where(business: @business, table: WorkoutSession.table_name).where.not(user: current_user) %>
<%= current_user.id %>
<% user_workout_changes = ChangeHistory.where(business: @business, table: UserWorkout.table_name).where.not(user: current_user) %>

<% changes_json = [] %>
<% changes_json << event_changes.to_json(include: { user: { include: :profile } }) %>
<% changes_json << user_workout_changes.to_json(include: { user: { include: :profile } }) %>

<% user_workouts = UserWorkout.unscoped.where(id: user_workout_changes.pluck(:row)).to_json %>
<% workouts = WorkoutSession.unscoped.where(id: event_changes.pluck(:row)) %>
<% workouts = workouts.or(WorkoutSession.unscoped.where(id: UserWorkout.unscoped.where(id: user_workout_changes.pluck(:row)).pluck(:workout_session_id))) %>
<% workouts = workouts.to_json %>

<% user_ids = event_changes.pluck(:user_id).uniq %>
<% gravatars = {} %>
<% gravatar_url = "https://secure.gravatar.com/avatar/" %>
<% user_ids.each do |uid| %>
  <% gravatars[uid] = gravatar_url + Digest::MD5::hexdigest(User.find(uid).email.downcase) %>
<% end %>

<div class="bg-white notifications-container">
  <div class="notification-header unselectable">
    Notifications

    <a class="clear-all" onclick="markAllAsRead();">
      mark all as read
    </a>
  </div>

  <div id="notifications" class="unselectable">
  </div>
</div>

<script>
  var BLANK_STRING = "(blank)";
  var TIME_FORMAT = "MMM D YYYY [at] hh:mma";
  var EVENT_NOTIFICATION_FORMAT = "dddd, MMMM Do YYYY [at] hh:mma";

  var NOTIFICATIONS_DIV = document.getElementById("notifications");
  var GRAVATAR_DEFAULT_SIZE = "?s=30"

  var MARK_ALL_READ_URL = "<%= business_mark_all_read_url(business_id: @business.slug) %>";
  var COLUMN_NAMES = <%= WorkoutSession.column_names.to_s.html_safe %>;


  var event_notifications_arr = JSON.parse('<%= changes_json[0].to_s.html_safe %>');
  var user_workout_notifications_arr = JSON.parse('<%= changes_json[1].to_s.html_safe %>');
  var notifications = {};

  var workouts = JSON.parse('<%= workouts.to_s.html_safe %>');
  var user_workouts = JSON.parse('<%= user_workouts.to_s.html_safe %>');
  var events_hash = {};

  var gravatars = <%= gravatars.to_json.to_s.html_safe %>;

  function markAllAsRead() {
    queryMarkAllAsRead();
  }

  function queryMarkAllAsRead() {
    $.ajax({
      type: "PATCH",
      url: MARK_ALL_READ_URL,
      dataType: "script",
      success: processMarkAllAsRead(),
      error: function() {
        errorMessage()
      }
    })
  }

  function initNotificationsHash() {
    hashNotifications(event_notifications_arr);
    hashNotifications(user_workout_notifications_arr);
  }

  function hashNotifications(arr) {
    for (var i = 0; i < arr.length; i++) {
      var key = arr[i]["user_id"];
      if (notifications[key] != null) {
        notifications[key].push(arr[i]);
      } else {
        notifications[key] = [arr[i]];
      }
    }
  }

  function processMarkAllAsRead() {
    console.log("Mark all as read");
  }

  function errorMessage() {
    console.log("Could not reach server for queryMarkAllAsRead");
  }

  function displayNotifications() {
    var notifications_keys = Object.keys(notifications);
    NOTIFICATIONS_DIV.innerHTML = "";

    if (notifications_keys.length > 0) {
      var ul = document.createElement("ul");
      ul.classList.add("notifications-ul");

      for (var i = notifications_keys.length-1; i >= 0; i--) {
        key = notifications_keys[i];

        if ( notifications[key].length > 0) {
          var li = document.createElement("li");

          var leading_img = document.createElement("div");
          leading_img.classList.add("leading-img");

          var img = document.createElement("img");
          img.classList.add("notifications-gravatar");
          img.src = getGravatar(key) + GRAVATAR_DEFAULT_SIZE;

          leading_img.append(img);

          var title = document.createElement("div");
          title.classList.add("title");
          title.innerHTML = getNotificationUserName(key, 0);
          title.innerHTML += " made " + changesAsString(notifications[key].length);

          li.append(leading_img);
          li.append(title);

          for (var j = notifications[key].length-1; j >= 0; j--) {
            var details = document.createElement("div");
            details.classList.add("details");
            details.classList.add(getNotificationReadStatus(key, j));

            var inner = getNotificationText(key,j );

            var time_span = document.createElement("div");
            time_span.classList.add("time");
            time_span.innerHTML = getNotificationTime(key, j);

            details.innerHTML = inner;
            details.append(time_span);


            li.append(details);
          }


          ul.append(li);
        }
      }

      NOTIFICATIONS_DIV.append(ul);
    } else {
      displayNoNotifications();
    }
  }

  function changesAsString(changes) {
    if (changes > 1) {
      return  changes + " changes."
    } else {
      return changes + " change."
    }
  }

  function getNotificationReadStatus(id, index) {
    if (notifications[id][index]["read"]) {
      return "read";
    } else {
      highlightBell();
      return "unread";
    }
  }

  function highlightBell() {
    var bell = document.getElementById("notification-bell");
    bell.classList.add("active");
  }

  function getNotificationText(id, index) {
    if (isWorkoutTable(id, index)) {
      return getWorkoutText(id, index);
    } else if (isUserWorkoutTable(id, index)) {
      return getUserWorkoutText(id, index);
    }

    return "";
  }

  function isWorkoutTable(id, index) {
    return notifications[id][index]["table"] == "<%= WorkoutSession.table_name %>";
  }

  function isUserWorkoutTable(id, index) {
      return notifications[id][index]["table"] == "<%= UserWorkout.table_name %>";
  }


  function getWorkoutText(id, index) {
    var notification = notifications[id][index];
    var code = notification["code"];

    var output = "";
    if (code == 0) {
      output += strongBlock("created") + " a session on " + getEventDate(notification["row"]) + ".";
    } else if (code == 18) {
      output += strongBlock("removed") + " a session on " + getEventDate(notification["row"]) + ".";
    } else if ([13, 6, 1].includes(code)) {
      output += strongBlock("changed") + " the " + COLUMN_NAMES[code] + " of a session " + previousValueBlock(valueOrBlank(notification["old_value"])) + " to " + currentValueBlock(valueOrBlank(notification["value"])) + ".";
    }

    return output;
  }

  function getUserWorkoutText(id, index) {
    var notification = notifications[id][index];
    var code = notification["code"];

    var output = "";

    if (code == 0 || (code == 18 && notification['value'] == "f")) {
      output += strongBlock("joined") + " a session on " + getUserWorkoutEventDate(notification['row']) + ".";
    } else if (code == 18) {
      output += strongBlock("left") + " a session on " + getUserWorkoutEventDate(notification['row']) + ".";
    }

    return output;
  }

  function strongBlock(inner) {
    var block = document.createElement("strong");
    block.innerHTML = inner;

    return block.outerHTML;
  }
  function previousValueBlock(inner) {
    if (inner != BLANK_STRING) {
      var block = document.createElement("code");
      block.classList.add("previous");
      block.innerHTML = inner;
      return " from " + block.outerHTML;
    }

    return "";
  }

  function currentValueBlock(inner) {
    var block = document.createElement("code");
    block.classList.add("current");
    block.innerHTML = inner;

    return block.outerHTML;
  }

  function getNotificationTime(id, index) {
    var notification = notifications[id][index];
    return moment(notification["updated_at"]).format(TIME_FORMAT);
  }

  function getEventDate(id) {
    return moment(events_hash[id]["date"]).format(EVENT_NOTIFICATION_FORMAT);
  }

  function getUserWorkoutEventDate(id) {
    var event_id = user_workouts_hash[id]["workout_session_id"];
    return getEventDate(event_id);
  }

  function getGravatar(id) {
    return gravatars[id];
  }

  function valueOrBlank(val) {
    if (val == null || val == "") {
      return BLANK_STRING;
    }

    return val;
  }

  function getNotificationUserName(id, index) {
    var email = notifications[id][index]["user"]["email"];
    var first = notifications[id][index]["user"]["profile"]["firstname"];
    var last = notifications[id][index]["user"]["profile"]["lastname"];

    output = email;
    if (first != null && first != "") {
      if (last != null && last != "") {
        output = first + " " + last[0] + ".";
      } else {
        output = first;
      }
    } else if (last != null && last != "") {
      output = last;
    }

    return output;
  }

  function displayNoNotifications() {
    var header = document.createElement("h5");
    header.innerHTML = "No notifications";
    NOTIFICATIONS_DIV.append(header);
  }

  function JSON2Hash(arr) {
    var output = {};
    for (var i = 0; i < arr.length; i++) {
      output[arr[i]["id"]] = arr[i];
    }
    return output;
  }

  function run() {
    events_hash = JSON2Hash(workouts);
    user_workouts_hash = JSON2Hash(user_workouts);
    initNotificationsHash();
    displayNotifications();
  }

  run();
</script>